name: pagewebaby runner
on:

  schedule:
    - cron: '0 8,20 * * *'
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: self-hosted
    timeout-minutes: 602

    strategy:
      fail-fast: false
      matrix:
        node-version: [16.x]


    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    #- run: kill -9 `lsof -w -n -i tcp:4204 | awk '$2!="PID" {print $2;}'`    
    - run: npm ci

    # Building the app in production mode
    - name: Build Angular App for Production
      run: npm run build -- --prod
      
    # Printing current directory  
    - name: Print Current Directory
      run: pwd

    # Setup SSH key and known hosts for secure deployment
    - name: Setup SSH Key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.NEW_PUB_KEY }}" > ~/.ssh/id_rsa.pub
        chmod 600 ~/.ssh/id_rsa.pub
        ssh-keyscan -Hv ${{ secrets.OVH_VPS_IP }} >> ~/.ssh/known_hosts 

    # Deploy the built application to the server
    - name: Deploy to Server
      run: |
            scp -r ./dist/* ubuntu@${{ secrets.OVH_VPS_IP }}:/home/ubuntu/pagewebaby/actions-runner/_work/pagewebaby/pagewebaby/
      #env:
      # SSH_PRIVATE_KEY: 

    # Optional: Restart Nginx to pick up new changes
    - name: Restart Nginx
      run: |
            ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.OVH_VPS_IP }} << 'EOF'
            sudo systemctl restart nginx
            pm2 describe pagewebaby > /dev/null
            if [ $? -eq 0 ]; then
                echo "pagewebaby is already managed by PM2, restarting..."
                pm2 restart pagewebaby --update-env
            else
                echo "pagewebaby is not managed by PM2, starting..."
                pm2 start npm --name pagewebaby -- run start
            fi
            pm2 save
            EOF
