name: pagewebaby runner
on:
  schedule:
    - cron: '0 8,20 * * *'
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    timeout-minutes: 602
    strategy:
      fail-fast: false
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install deps
        run: npm ci

      # Twój build – zostawiasz jak jest (bo tworzy też dist/pagewebaby/basketball-pwa/)
      - name: Build Angular App for Production
        run: npm run build -- --prod

      # (opcjonalnie) pokaż, że PWA jest w dist/
      - name: Show PWA build
        run: ls -lah dist/pagewebaby/basketball-pwa || true

      # ► DEPLOY LOKALNY zamiast scp
      - name: Deploy dist/ to Nginx docroot
        run: |
          rsync -az --delete ./dist/ \
            /home/ubuntu/pagewebaby/actions-runner/_work/pagewebaby/pagewebaby/

      # ► Poprawny reload Nginx
      - name: Reload Nginx
        run: sudo nginx -t && sudo systemctl reload nginx

      # (opcjonalnie) szybka weryfikacja po stronie serwera
      - name: Verify deployed files
        run: |
          ls -lah /home/ubuntu/pagewebaby/actions-runner/_work/pagewebaby/pagewebaby/pagewebaby | head -n 50
          echo "---- /basketball-pwa ----"
          ls -lah /home/ubuntu/pagewebaby/actions-runner/_work/pagewebaby/pagewebaby/pagewebaby/basketball-pwa | head -n 50
