name: pagewebaby runner
on:

  schedule:
    - cron: '59 4,9,15,19 * * *'
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: self-hosted
    timeout-minutes: 602

    strategy:
      fail-fast: false
      matrix:
        node-version: [16.x]


    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm start
