name: pagewebaby runner

on:
  schedule:
    - cron: '0 8,20 * * *'
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    timeout-minutes: 602
    strategy:
      fail-fast: false
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install deps (site)
        run: npm ci

      - name: Build site (production)
        run: npx ng build --configuration production --base-href / --deploy-url /

      # ───────── PWA z drugiego repo ─────────
      - name: Checkout PWA repo
        uses: actions/checkout@v4
        with:
          repository: maciejmar/basketball-game
          path: pwa

      - name: Install deps (PWA)
        working-directory: pwa
        run: npm ci

      - name: Build PWA (production)
        working-directory: pwa
        run: npx ng build --configuration production --base-href /basketball-pwa/ --deploy-url /basketball-pwa/

      - name: Find PWA build dir
        id: pwadir
        shell: bash
        run: |
          if compgen -G "pwa/dist/*/browser/basketball-pwa" > /dev/null; then
            echo "dir=$(ls -d pwa/dist/*/browser/basketball-pwa)" >> $GITHUB_OUTPUT
          elif compgen -G "pwa/dist/*/basketball-pwa" > /dev/null; then
            echo "dir=$(ls -d pwa/dist/*/basketball-pwa)" >> $GITHUB_OUTPUT
          else
            echo "PWA build not found"; exit 1
          fi

      - name: Put PWA into site's dist
        run: |
          mkdir -p dist/pagewebaby/basketball-pwa
          rsync -a --delete "${{ steps.pwadir.outputs.dir }}/" dist/pagewebaby/basketball-pwa/

      # ───────── Deploy ─────────
      - name: Deploy dist/ to server docroot parent
        shell: bash
        run: |
          rsync -az --delete ./dist/ \
            /home/ubuntu/pagewebaby/actions-runner/_work/pagewebaby/pagewebaby/ || EXIT=$?
          # rsync czasem zwraca 24 (vanished) – nie traktuj jako błąd
          if [ "${EXIT:-0}" != "0" ] && [ "$EXIT" != "24" ]; then exit "$EXIT"; fi

      - name: Reload Nginx
        run: sudo nginx -t && sudo systemctl reload nginx

      - name: Verify deployed files
        run: |
          ls -lah /home/ubuntu/pagewebaby/actions-runner/_work/pagewebaby/pagewebaby/pagewebaby | head -n 50
          echo "---- /basketball-pwa ----"
          ls -lah /home/ubuntu/pagewebaby/actions-runner/_work/pagewebaby/pagewebaby/pagewebaby/basketball-pwa | head -n 50
