name: pagewebaby runner

on:
  schedule:
    - cron: '0 8,20 * * *'
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    timeout-minutes: 602
    strategy:
      fail-fast: false
      matrix:
        node-version: [20.x]   # <── Angular CLI wymaga ≥ 18.13, dajemy 20.x

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - run: node -v && npm -v

      # ─── Build strony (root)
      - name: Install deps (site)
        run: npm ci

      - name: Build site (production)
        run: npx ng build --configuration production --base-href / --deploy-url /

      # ─── Build PWA (podfolder: basketball-pwa/)
      - name: Install deps (PWA)
        working-directory: basketball-pwa
        run: npm ci

      - name: Build PWA (production)
        working-directory: basketball-pwa
        run: npx ng build --configuration production --base-href /basketball-pwa/ --deploy-url /basketball-pwa/

      # Wyciągnij folder wyjściowy PWA (Angular 16/17 czasem daje .../browser)
      - name: Find PWA build dir
        id: pwadir
        shell: bash
        run: |
          cd basketball-pwa
          if compgen -G "dist/*/browser" > /dev/null; then
            echo "dir=$(ls -d dist/*/browser)" >> $GITHUB_OUTPUT
          else
            echo "dir=$(ls -d dist/*)" >> $GITHUB_OUTPUT
          fi

      # Włóż PWA do dist/pagewebaby/basketball-pwa/
      - name: Put PWA into site's dist
        run: |
          mkdir -p dist/pagewebaby/basketball-pwa
          rsync -a --delete "${{ steps.pwadir.outputs.dir }}/" dist/pagewebaby/basketball-pwa/

      # ─── Deploy lokalny (runner = ten sam serwer)
      - name: Deploy dist/ to Nginx docroot parent
        shell: bash
        run: |
          rsync -az --delete ./dist/ \
            /home/ubuntu/pagewebaby/actions-runner/_work/pagewebaby/pagewebaby/ || EXIT=$?
          # toleruj rsync code 24 (vanished)
          if [ "${EXIT:-0}" != "0" ] && [ "$EXIT" != "24" ]; then exit "$EXIT"; fi

      - name: Reload Nginx
        run: sudo nginx -t && sudo systemctl reload nginx

      - name: Verify deployed files
        run: |
          ls -lah /home/ubuntu/pagewebaby/actions-runner/_work/pagewebaby/pagewebaby/pagewebaby | head -n 50
          echo "---- /basketball-pwa ----"
          ls -lah /home/ubuntu/pagewebaby/actions-runner/_work/pagewebaby/pagewebaby/pagewebaby/basketball-pwa | head -n 50
