name: pagewebaby runner
on:

  schedule:
    - cron: '59 4,9,15,19 * * *'
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: self-hosted
    timeout-minutes: 602

    strategy:
      fail-fast: false
      matrix:
        node-version: [16.x]


    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    #- run: kill -9 `lsof -w -n -i tcp:4204 | awk '$2!="PID" {print $2;}'`    
    - run: npm ci

    # Building the app in production mode
    - name: Build Angular App for Production
      run: npm run build -- --prod

    # Setup SSH key and known hosts for secure deployment
    - name: Setup SSH Key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.OVH_VPS_IP }} >> ~/.ssh/known_hosts 

    # Deploy the built application to the server
    - name: Deploy to Server
      run:  rsync -avz --delete ./dist/pagewebaby/ ubuntu@${{ secrets.OVH_VPS_IP }}:/home/ubuntu/pagewebaby/actions-runner/_work/pagewebaby/pagewebaby/

    # Optional: Restart Nginx to pick up new changes
    - name: Restart Nginx
      run:  ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.OVH_VPS_IP }} << 'EOF'
    - run:  sudo systemctl restart nginx
    - run:  npm run pm2-check
    - run:  npm run pm2-restart
